
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - slipway.k8s.facebook.com
  resources:
  - imagemirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slipway.k8s.facebook.com
  resources:
  - imagemirrors/status
  verbs:
  - get
  - patch
  - update
