apiVersion: slipway.k8s.facebook.com/v1
kind: ImageMirror
metadata:
  name: centos
spec:
  sourceRepository: docker.io/
  destRepository: dtr.thefacebook.com/dwat/
  imageName: centos
  pattern: "semver: ~7"
