apiVersion: slipway.k8s.facebook.com/v1
kind: ImageMirror
metadata:
  name: centos
spec:
  sourceRepo: docker.io
  #destRepo: dtr.thefacebook.com/dwat/
  destRepo: docker.io/dwat/
  imageName: centos
  pattern: "semver: ~7"
  destSecretName: docker-registry-token
